CREATE TABLE User (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL,
	phone VARCHAR(32),
	first_name VARCHAR(255),
	last_name VARCHAR(255),
	role INT UNSIGNED NOT NULL,
	password VARCHAR(8192),
	PRIMARY KEY (id),
	FOREIGN KEY (role) REFERENCES Role(id)
)

CREATE TABLE Role (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
    label VARCHAR(255) NOT NULL
)